### ISSUE TITLE
SQL injections possible

### ISSUE THREAD

**Issue by StRKri** [litzinetz-de/OpenVoucher#27]
At several points of the code, SQL-commands are generated by inserting POSTed Strings to a SQL statement. --> This code is highly vulnerable for SQL injections!

(see: https://en.wikipedia.org/wiki/SQL_injection)

**Comment by litzinetz-de** [comment]
Hi there,

i know what SQL injections are ;) and i also know that this code is
vulnerable. That's why we call that a BETA ;)

At the moment, i'm not maintaining the code. Feel free to fork it and
fix the problems, if you want to.

Thanks for your Mail.

Regards

Daniel

**Comment by litzinetz-de** [comment]
Has been fixed in 1.0.0
